import { Search, SlidersHorizontal } from 'lucide-react'
import { useMemo, useState } from 'react'
import { DataPage } from '../components/common/index.ts'
import { employeeRecords } from '../services/workspaceData.ts'

export function EmployeeDirectory() {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('All')
  const filtered = useMemo(() => employeeRecords.filter((employee) => `${employee.name} ${employee.role} ${employee.department} ${employee.skills.join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All' || employee.status === status)), [query, status])
  return <DataPage eyebrow="People" title="Employee directory" description="Understand the people, skills, and capacity available to your projects."><section className="data-panel"><div className="toolbar"><label className="field search-field"><Search size={16} /><input aria-label="Search employees" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by name, role, or skill" /></label><label className="field"><SlidersHorizontal size={16} /><select aria-label="Filter availability" value={status} onChange={(event) => setStatus(event.target.value)}><option>All</option><option>Available</option><option>Limited</option><option>Unavailable</option></select></label><span className="toolbar-count">{filtered.length} of {employeeRecords.length}</span></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Role</th><th>Department</th><th>Skills</th><th>Workload</th><th>Capacity</th><th>Change</th><th>Status</th></tr></thead><tbody>{filtered.slice(0, 100).map((employee) => <tr key={employee.id}><td><strong>{employee.name}</strong><small>{employee.code}</small></td><td>{employee.role}</td><td>{employee.department}</td><td><div className="tag-list">{employee.skills.slice(0, 3).map((skill) => <span className="tag" key={skill}>{skill}</span>)}</div></td><td><div className="meter"><i style={{ width: `${employee.workload}%` }} /></div>{employee.workload}%</td><td>{employee.capacity}%</td><td className={employee.capacityChange < 0 ? 'text-danger' : 'text-success'}>{employee.capacityChange > 0 ? '+' : ''}{employee.capacityChange}%</td><td><span className={`status ${employee.status.toLowerCase()}`}>{employee.status}</span></td></tr>)}</tbody></table></div></section></DataPage>
}
